<?php
/**
 * WP_Theme theme settings
 *
 * @package WordPress
 * @subpackage WP_Theme
 * @since 1.0.0
 */
?>

<?php

if (function_exists('acf_add_options_page')) {
    // Global Options
    acf_add_options_page([
        'page_title'    =>  __('WP_Theme Options', 'wp_theme'),
        'menu_title'    =>  __('WP_Theme Options', 'wp_theme'),
        'menu_slug'     =>  'theme-options',
        'position'      =>  '100',
        'capability'    =>  'edit_posts',
        'redirect'      =>  false,
    ]);

    acf_add_options_sub_page([
        'page_title'    =>  __('Advanced', 'wp_theme'),
        'menu_title'    =>  __('Advanced', 'wp_theme'),
        'parent_slug'   =>  'theme-options',
    ]);
}

if (function_exists('acf_add_local_field_group')) {
    // Themes options
    acf_add_local_field_group([
        'key'                   =>  'group_options',
        'title'                 =>  __('Theme Options - Options', 'wp_theme'),
        'fields'                =>  [
            [
                'key'               =>  'field_66mf9e94f0a7b',
                'label'             =>  __('Base options', 'wp_theme'),
                'name'              =>  '',
                'type'              =>  'tab',
                'instructions'      =>  '',
                'required'          =>  0,
                'conditional_logic' =>  0,
                'wrapper'           =>  [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
            ],
            [
                'key'               =>  'field_5b5accd2baefe',
                'label'             =>  __('Links', 'wp_theme'),
                'name'              =>  'opt__links',
                'type'              =>  'repeater',
                'instructions'      =>  '',
                'required'          =>  0,
                'conditional_logic' =>  0,
                'wrapper'           =>  [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'collapsed'         =>  'field_5b5accecbaeff',
                'min'               =>  0,
                'max'               =>  0,
                'layout'            =>  'table',
                'button_label'      =>  '',
                'sub_fields'        =>  [
                    [
                        'key'               =>  'field_5b5accecbaeff',
                        'label'             =>  __('Text', 'wp_theme'),
                        'name'              =>  'opt__links_text',
                        'type'              =>  'text',
                        'instructions'      =>  '',
                        'required'          =>  0,
                        'conditional_logic' =>  0,
                        'wrapper'           =>  [
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ],
                        'default_value'     =>  '',
                        'placeholder'       =>  '',
                        'prepend'           =>  '',
                        'append'            =>  '',
                        'maxlength'         =>  '',
                    ],
                    [
                        'key'               =>  'field_5b5accfdbaf00',
                        'label'             =>  __('Link', 'wp_theme'),
                        'name'              =>  'opt__links_link',
                        'type'              =>  'page_link',
                        'instructions'      =>  '',
                        'required'          =>  0,
                        'conditional_logic' =>  0,
                        'wrapper'           =>  [
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ],
                        'post_type'         =>  [
                            0 => 'page',
                        ],
                        'taxonomy'          =>  [],
                        'allow_null'        =>  1,
                        'allow_archives'    =>  0,
                        'multiple'          =>  0,
                    ],
                ],
            ],
            [
                'key'               =>  'field_5b05496a67845',
                'label'             =>  __('Email', 'wp_theme'),
                'name'              =>  'opt__email',
                'type'              =>  'email',
                'instructions'      =>  '',
                'required'          =>  0,
                'conditional_logic' =>  0,
                'wrapper'           =>  [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
                'default_value'     =>  '',
                'placeholder'       =>  '',
                'prepend'           =>  '',
                'append'            =>  '',
            ],
            [
                'key'               =>  'field_51mf9e94f0a7b',
                'label'             =>  __('Logo in header', 'wp_theme'),
                'name'              =>  'opt__logo',
                'type'              =>  'image',
                'required'          =>  0,
                'conditional_logic' =>  0,
            ],
            [
                'key'               =>  'field_53mf9e94f0a7b',
                'label'             =>  __('Copyright', 'wp_theme'),
                'name'              =>  'opt__copyright',
                'type'              =>  'text',
                'required'          =>  0,
                'conditional_logic' =>  0,
            ],
            [
                'key'               =>  'field_57mf9e94f0a7b',
                'label'             =>  __('Social links', 'wp_theme'),
                'name'              =>  '',
                'type'              =>  'tab',
                'instructions'      =>  '',
                'required'          =>  0,
                'conditional_logic' =>  0,
                'wrapper'           =>  [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
            ],
            [
                'key'               =>  'field_65mf9e94f0a7b',
                'label'             =>  __('Google+', 'wp_theme'),
                'name'              =>  'opt__social_gplus',
                'type'              =>  'url',
                'instructions'      =>  '',
                'required'          =>  0,
                'conditional_logic' =>  0,
                'wrapper'           =>  [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
            ],
            [
                'key'               =>  'field_61mf9e94f0a7b',
                'label'             =>  __('LinkedIn', 'wp_theme'),
                'name'              =>  'opt__social_linkedin',
                'type'              =>  'url',
                'instructions'      =>  '',
                'required'          =>  0,
                'conditional_logic' =>  0,
                'wrapper'           =>  [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
            ],
            [
                'key'               =>  'field_62mf9e94f0a7b',
                'label'             =>  __('Twitter', 'wp_theme'),
                'name'              =>  'opt__social_twitter',
                'type'              =>  'url',
                'instructions'      =>  '',
                'required'          =>  0,
                'conditional_logic' =>  0,
                'wrapper'           =>  [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
            ],
            [
                'key'               =>  'field_63mf9e94f0a7b',
                'label'             =>  __('Telegram', 'wp_theme'),
                'name'              =>  'opt__social_telegram',
                'type'              =>  'url',
                'instructions'      =>  '',
                'required'          =>  0,
                'conditional_logic' =>  0,
                'wrapper'           =>  [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
            ],
            [
                'key'               =>  'field_642mf9e94f0a7b',
                'label'             =>  __('Bitcointalk', 'wp_theme'),
                'name'              =>  'opt__social_bitcointalk',
                'type'              =>  'url',
                'instructions'      =>  '',
                'required'          =>  0,
                'conditional_logic' =>  0,
                'wrapper'           =>  [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
            ],
            [
                'key'               =>  'field_65mf9e94f0a7b',
                'label'             =>  __('Medium', 'wp_theme'),
                'name'              =>  'opt__social_medium',
                'type'              =>  'url',
                'instructions'      =>  '',
                'required'          =>  0,
                'conditional_logic' =>  0,
                'wrapper'           =>  [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
            ],
            [
                'key'               =>  'field_65mf9e94f0a7b',
                'label'             =>  __('Facebook', 'wp_theme'),
                'name'              =>  'opt__social_facebook',
                'type'              =>  'url',
                'instructions'      =>  '',
                'required'          =>  0,
                'conditional_logic' =>  0,
                'wrapper'           =>  [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
            ],
	        [
		        'key'               =>  'field_65mf9e94f0a7b',
		        'label'             =>  __('VK', 'wp_theme'),
		        'name'              =>  'opt__social_vk',
		        'type'              =>  'url',
		        'instructions'      =>  '',
		        'required'          =>  0,
		        'conditional_logic' =>  0,
		        'wrapper'           =>  [
			        'width' => '',
			        'class' => '',
			        'id'    => '',
		        ],
	        ],
            [
                'key'               =>  'field_69mf9e94f0a7b',
                'label'             =>  __('Cookies', 'vnx'),
                'name'              =>  '',
                'type'              =>  'tab',
                'instructions'      =>  '',
                'required'          =>  0,
                'conditional_logic' =>  0,
                'wrapper'           =>  [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
            ],
            [
                'key'               =>  'field_5b50be54d96a9',
                'label'             =>  __('Show Cookie Alert', 'wp_theme'),
                'name'              =>  'opt__cookies_show',
                'type'              =>  'true_false',
                'instructions'      =>  '',
                'required'          =>  0,
                'conditional_logic' =>  0,
                'wrapper'           =>  [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
                'message'           =>  '',
                'default_value'     =>  0,
                'ui'                =>  1,
                'ui_on_text'        =>  __('Show', 'wp_theme'),
                'ui_off_text'       =>  __('Hide', 'wp_theme'),
            ],
            [
                'key'               =>  'field_5b50bf71d96aa',
                'label'             =>  __('Alert Text', 'wp_theme'),
                'name'              =>  'opt__cookies_text',
                'type'              =>  'text',
                'instructions'      =>  '',
                'required'          =>  0,
                'conditional_logic' =>  0,
                'wrapper'           =>  [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
                'default_value'     =>  '',
                'placeholder'       =>  '',
                'prepend'           =>  '',
                'append'            =>  '',
                'maxlength'         =>  '',
            ]
        ],
        'location'              =>  [
            [
                [
                    'param'     =>  'options_page',
                    'operator'  =>  '==',
                    'value'     =>  'theme-options',
                ],
            ],
        ],
        'menu_order'            =>  0,
        'position'              =>  'normal',
        'style'                 =>  'default',
        'label_placement'       =>  'left',
        'instruction_placement' =>  'label',
        'hide_on_screen'        =>  '',
        'active'                =>  1,
        'description'           =>  '',
    ]);

    // Styles and scripts
    acf_add_local_field_group([
        'key'                   =>  'group_advanced',
        'title'                 =>  __('Theme Options - Advanced', 'wp_theme'),
        'fields'                =>  [
            [
                'key'               =>  'field_56bf9dd0d7636',
                'label'             =>  __('Metrics', 'wp_theme'),
                'name'              =>  '',
                'type'              =>  'tab',
                'instructions'      =>  '',
                'required'          =>  0,
                'conditional_logic' =>  0,
                'wrapper'           =>  [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
                'placement'         =>  'top',
                'endpoint'          =>  0,
            ],
            [
                'key'               =>  'field_56bf9b94f0a7b',
                'label'             =>  __('Yandex.Metrika tracking code', 'wp_theme'),
                'name'              =>  'opt__yandex_metrika',
                'type'              =>  'textarea',
                'instructions'      =>  __('The code will be added after the opening tag body.<br>Added with script tag.', 'wp_theme'),
                'required'          =>  0,
                'conditional_logic' =>  0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
                'default_value'     =>  '',
                'placeholder'       =>  '',
                'maxlength'         =>  '',
                'rows'              =>  '',
                'new_lines'         =>  '',
            ],
            [
                'key'               =>  'field_56bf9c05f0a7d',
                'label'             =>  __('Google Analytics tracking code', 'wp_theme'),
                'name'              =>  'opt__google_analytics',
                'type'              =>  'textarea',
                'instructions'      =>  __('The code will be added before the closing head tag.<br>Added with script tag.', 'wp_theme'),
                'required'          =>  0,
                'conditional_logic' =>  0,
                'wrapper'           =>  [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
                'default_value'     =>  '',
                'placeholder'       =>  '',
                'maxlength'         =>  '',
                'rows'              =>  '',
                'new_lines'         =>  '',
            ],
            [
                'key'               =>  'field_5a09bb94eb42f',
                'label'             =>  __('Other scripts', 'wp_theme'),
                'name'              =>  '',
                'type'              =>  'tab',
                'instructions'      =>  '',
                'required'          =>  0,
                'conditional_logic' =>  0,
                'wrapper'           =>  [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
                'placement'         =>  'top',
                'endpoint'          =>  0,
            ],
            [
                'key'               =>  'field_5a09bbe4eb430',
                'label'             =>  __('Scripts before', 'wp_theme') . '&lt;/head&gt;',
                'name'              =>  'opt__ScriptsBeforeHeadClose',
                'type'              =>  'code',
                'instructions'      =>  __('The code will be added before the closing head tag.', 'wp_theme'),
                'required'          =>  0,
                'conditional_logic' =>  0,
                'wrapper'           =>  [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
                'language'          =>  'javascript',
                'theme'             =>  'monokai',
            ],
            [
                'key'               =>  'field_5a09bc74eb431',
                'label'             =>  __('Scripts after', 'wp_theme') . '&lt;body&gt;',
                'name'              =>  'opt__ScriptsAfterBodyOpen',
                'type'              =>  'code',
                'instructions'      =>  __('The code will be added after the opening tag body.', 'wp_theme'),
                'required'          =>  0,
                'conditional_logic' =>  0,
                'wrapper'           =>  [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
                'language'          =>  'javascript',
                'theme'             =>  'monokai',
            ],
            [
                'key'               =>  'field_5a09bca2eb432',
                'label'             =>  __('Scripts before', 'wp_theme') . '&lt;/body&gt;',
                'name'              =>  'opt__ScriptsBeforeBodyClose',
                'type'              =>  'code',
                'instructions'      =>  __('The code will be added before the closing body tag.', 'wp_theme'),
                'required'          =>  0,
                'conditional_logic' =>  0,
                'wrapper'           =>  [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
                'language'          =>  'javascript',
                'theme'             =>  'monokai',
            ],
            [
                'key'               =>  'field_56bf9de1d7637',
                'label'             =>  __('Custom css', 'wp_theme'),
                'name'              =>  '',
                'type'              =>  'tab',
                'instructions'      =>  '',
                'required'          =>  0,
                'conditional_logic' =>  0,
                'wrapper'           =>  [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
                'placement'         =>  'top',
                'endpoint'          =>  0,
            ],
            [
                'key'               =>  'field_56bf95094dcb1',
                'label'             =>  __('Custom css', 'wp_theme'),
                'name'              =>  'opt__code_css',
                'type'              =>  'code',
                'instructions'      =>  __('The option is designed to insert arbitrary css code to add new properties or change existing ones. Syntax highlighting works. The code will be added before the closing tag </head>', 'wp_theme'),
                'required'          =>  0,
                'conditional_logic' => 0,
                'wrapper'           =>  [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
                'language'          =>  'css',
                'theme'             =>  'monokai',
            ],
        ],
        'location'              =>  [
            [
                [
                    'param'     =>  'options_page',
                    'operator'  =>  '==',
                    'value'     =>  'acf-options-advanced',
                ],
            ],
        ],
        'menu_order'            =>  0,
        'position'              =>  'normal',
        'style'                 =>  'default',
        'label_placement'       =>  'left',
        'instruction_placement' =>  'label',
        'hide_on_screen'        =>  '',
        'active'                =>  1,
        'description'           =>  '',
    ]);
}